[versions]

ktx = "1.12.0"
app-compat = "1.6.1"
kotlin-bom = "1.8.0"
lifecycle-runtime-ktx = "2.6.1"
material-2 = "1.10.0"
junit = "4.13.2"
mockito = "5.7.0"
truth = "1.1"
android-junit = "1.1.5"
espresso = "3.5.1"
activity-compose = "1.7.2"
coil-compose = "2.4.0"
compose-bom = "2024.02.02"
composereorderable = "0.9.6"
ui-tooling = "1.6.0"
accompanist-systemuicontroller = "0.27.0"
accompanist-navigation-animation = "0.30.0"
material-icons-extended = "1.4.3"
hilt-android = "2.44"
hilt-navigation-compose = "1.0.0"
coroutines = "1.7.1"
firebase-bom = "32.2.0"
security-crypto = "1.0.0"
gson = "2.10.1"
retrofit = "2.9.0"
arrow = "1.1.2"
splashscreen = "1.0.1"
agp = "8.1.0-rc01"
org-jetbrains-kotlin-android = "1.7.20"

[libraries]

#Android/Kotlin
androidx-ktx = { module = "androidx.core:core-ktx", version.ref = "ktx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "app-compat" }
org-jetbrains-kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin-bom" }
com-google-material = { module = "com.google.android.material:material", version.ref = "material-2" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }

#Lifecycle
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle-runtime-ktx" }

#Tests
junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "android-junit" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
google-truth = { module = "com.google.truth:truth", version.ref = "truth" }

#Compose
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "ui-tooling" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "ui-tooling" }
androidx-compose-ui-test-junit = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-icons-extended" }
io-coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
burnoutcrew-composereorderable = { module = "org.burnoutcrew.composereorderable:reorderable", version.ref = "composereorderable" }

#Accompanist
com-google-accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist-systemuicontroller" }
com-google-accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist-navigation-animation" }

#Hilt
com-google-dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
com-google-dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt-android" }

#Coroutines
org-jetbrains-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
org-jetbrains-kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
org-jetbrains-kotlinx-coroutines-playservices = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines" }

#Firebase
com-google-firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
com-google-firebase-databasektx = { module = "com.google.firebase:firebase-database-ktx" }
com-google-firebase-authktx = { module = "com.google.firebase:firebase-auth-ktx" }
com-google-firebase-analyticsktx = { module = "com.google.firebase:firebase-analytics-ktx" }
com-google-firebase-crashlyticsktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }

#Secure datastore
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "security-crypto" }
com-google-code-gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

#Retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-json = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }


[plugins]
com-android-library = { id = "com.android.library", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }